---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bytestash
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://jordan-dalby.github.io/ByteStash/
