---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://helm.openwebui.com/


