---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://kyverno.github.io/kyverno/
