---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-0.23.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    config:
      data:
        INHERITED_LABELS: "prometheus.kommander.d2iq.io/select"
