---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ollama
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: ${releaseNamespace}
      version: 1.25.0
  interval: 1m0s
  install:
    createNamespace: true
    crds: CreateReplace
  targetNamespace: ollama
  releaseName: ollama
  valuesFrom:
    - kind: ConfigMap
      name: ollama-1.14.0-defaults
    - kind: ConfigMap
      name: ollama-overrides
      optional: true
