---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: ${releaseNamespace}
      version: 3.5.1
  install:
    createNamespace: true
    crds: CreateReplace
  interval: 1m0s
  targetNamespace: kyverno
  releaseName: kyverno
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-3.4.1-defaults
    - kind: ConfigMap
      name: kyverno-overrides
      optional: true
