apiVersion: v1
data:
  values.yaml: |
    infisical:
      image:
        repository: infisical/infisical
        tag: "v0.155.5"
        pullPolicy: IfNotPresent
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
---

