---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flowise
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: flowise
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flowise
        namespace: ${releaseNamespace}
      version: 2.6.0
  interval: 1m0s
  targetNamespace: ${releaseNamespace}
  releaseName: flowise
  valuesFrom:
    - kind: ConfigMap
      name: flowise-2.6.0-defaults
    - kind: ConfigMap
      name: flowise-overrides
      optional: true
