---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flowise
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://cowboysysop.github.io/charts/
