---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: grafana-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-operator
        namespace: ${releaseNamespace}
      version: v5.18.0
  interval: 1m0s
  install:
    createNamespace: true
    crds: CreateReplace
  targetNamespace: grafana-operator
  releaseName: grafana-operator
  valuesFrom:
    - kind: ConfigMap
      name: grafana-operator-5.17.1-defaults
    - kind: ConfigMap
      name: grafana-operator-overrides
      optional: true
