---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: gpu-operator-charts
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rocm
        namespace: ${releaseNamespace}
      version: 1.3.0
  interval: 1m0s
  targetNamespace: kube-amd-gpu
  install:
    createNamespace: true
    crds: CreateReplace
  releaseName: amd-gpu-operator
  valuesFrom:
    - kind: ConfigMap
      name: amd-gpu-operator-1.3.0-defaults
    - kind: ConfigMap
      name: amd-gpu-operator-overrides
      optional: true
