---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-1.5.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ollama:
      gpu:
        enabled: true

    persistentVolume:
      enabled: true
      size: 100Gi