---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rocm
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://rocm.github.io/gpu-operator
