---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anything-llm
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: https://la-cc.github.io/anything-llm-helm-chart
---

