---
apiVersion: v1
kind: ConfigMap
metadata:
  name: services-5.23.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ingress:
      enabled: false
    service:
      type: LoadBalancer
    ollama:
      ollama:
        gpu:
          enabled: "true"
        models:
          pull:
            - mistral
    